### ISSUE TITLE
minimize, maximize, and close buttons did not migrate to the One Bar

### ISSUE THREAD

**Issue by circuitsystem** [FawazBinSaleem/FireFoxOneLinerCSS#1]
they remain atop the area that they should have migrated to

![fox](https://github.com/user-attachments/assets/3ba64995-1a9b-46ab-8762-a9608b95ebd3)

**Comment by FawazBinSaleem** [comment]
I tested this on Windows 11, it seems to be all on one line over there, I can't test for macOS but it the minimize,resize buttons are also not on one bar in my Linux machine so I'll try to see if I can fix it.

**Comment by FawazBinSaleem** [comment]
Found a potential fix (works for linux mint 22) but try it on your MAC
go to `about:config`and type `browser.tabs.inTitlebar` and set the value to 1.
That seemed to work for me.
![Screenshot from 2024-09-13 18-31-47](https://github.com/user-attachments/assets/a8469a64-27e3-439b-975f-6a76a59feba0)

userChrome cant modify the titleBar text since it depends on your OS but after you enable the setting, the close,minimize and resize buttons should migrate all in one line.
